### ISSUE TITLE
Print accross multiple pages

### ISSUE THREAD

**Issue by andymac-2** [andymac-2/trakMap#17]
Add ability to print across multiple pages instead of just a single page.

**Comment by PritchardBarry** [comment]
1. After bringing up the print dialog a second time it does not let me print more than one page.
2. Does not appear to print in landscape. Might be the local printer.

**Comment by PritchardBarry** [comment]
Only occurs in Safari. Chrome is working OK.

**Comment by PritchardBarry** [comment]
"XL Landscape" appears to print just over the page boundary. See attached.
[Trak Map.pdf](https://github.com/andymac-2/trakMap/files/3492300/Trak.Map.pdf)

**Comment by andymac-2** [comment]
I can't reproduce bug 1. Safari allows me to print multiple pages every time. As for Bug 2, you have to manually select Landscape from the print dialog. The web browser has no control over page orientation when printing.
