### ISSUE TITLE
Adding days for no reason?

### ISSUE THREAD

**Issue by PritchardBarry** [andymac-2/trakMap#18]
I have been creating a trakmap based on weeks (multiples of 7). 

For some reason the durations appear to change.

![D5A04511-6742-4C5F-A284-AE1EF6800F00](https://user-images.githubusercontent.com/38608315/62702452-597fb080-ba19-11e9-9f3f-f0b7eafb94da.jpeg)
![993967BB-A79A-46B5-80F2-3CD83346E9EC](https://user-images.githubusercontent.com/38608315/62702454-597fb080-ba19-11e9-9fe8-6e894a36cf56.jpeg)

**Comment by PritchardBarry** [comment]
Correction. The "31" was 28.

**Comment by andymac-2** [comment]
Can you let me know:

* What browser you're using
* What steps cause the dates to change
* the json  save file?

**Comment by andymac-2** [comment]
@PritchardBarry Alternatively go to Web developer -> Console and let me know if anything is there.

**Comment by PritchardBarry** [comment]
Happened in Chrome on a Windows machine and Safari on iPad. 

It is almost as if the days are incremented by the “proportioning” method. 

 It sure exactly when it happens. I noticed it while I was adding and updating. I corrected and saved. I reopened the file and it appeared ok but then I did it again later and the opened file has the issue.
