### ISSUE TITLE
Change to status to cater for"greedy" mode

### ISSUE THREAD

**Issue by PritchardBarry** [andymac-2/trakMap#19]
In greedy mode the mechanism for showing% complete and health is misleading since it applies to the date note prior.

Can we have a health and % complete indicator over the text instead or apply the indicator and % too the line. 
![A934C003-EC8C-4A96-88E3-3AA19F3F3BC6](https://user-images.githubusercontent.com/38608315/62746219-1e18cc80-ba81-11e9-941a-e92368373c83.jpeg)

**Comment by PritchardBarry** [comment]
Latest change is great.

Couple of minor tweaks.

1. When complete (100%) fill the entire bar in grey.
2. Can the fill be black instead of the priority line colour. This is because red indicates "bad". So if we just make the progress/health bar always the same colour this will work.

**Comment by andymac-2** [comment]
Black is a very strong colour, and can draw a bit too much attention in my opinion. Personally maybe a grey would be better?

I have created three options to choose from to get an idea of what we could do. Check the branches when you have time.

**Comment by PritchardBarry** [comment]
Sounds great, I will look at it tonight.

**Comment by andymac-2** [comment]
Fixed see 0542d90
