### ISSUE TITLE
Create backward dependency

### ISSUE THREAD

**Issue by PritchardBarry** [andymac-2/trakMap#2]
Can we add a product from the end point?

e.g. Create one from Mar 10 from "Proof of Value" or Mar 10 from "Solution Vision" in the image below.

![190220_01tm](https://user-images.githubusercontent.com/38608315/53081559-12b70080-3536-11e9-94bf-c79730764049.png)

**Comment by andymac-2** [comment]
Yes. Switch modes to lazy mode, and then you can create backward dependencies. Note that it doesn't make sense to make a backward dependency from the end of a product, or a forward dependency from the start of a product. The closest thing is to create a milestone where the start and end are the same.

**Comment by andymac-2** [comment]
Closing, either this has been resolved, or is not part of the design of the system.
