### ISSUE TITLE
Display duration in weeks

### ISSUE THREAD

**Issue by PritchardBarry** [andymac-2/trakMap#29]
Can we get an option to display the duration in the label in weeks.

I.e. we still enter in days but the labels in brackets displays in weeks.

E.g. 84 days = 12 weeks,
![843E61AA-E664-4D2F-8087-F9F6393D349E](https://user-images.githubusercontent.com/38608315/67154245-7eeb3d80-f32b-11e9-86f9-a515b809215e.png)

**Comment by PritchardBarry** [comment]
.... can be displayed as “(12w)”

**Comment by andymac-2** [comment]
Did you want the option to display duration in weeks, or do you just want it hardcoded?

I was thinking 17 days would be `2(3)` (2 weeks, 3 days)

**Comment by andymac-2** [comment]
Format candidates for 17 days:
- ISO8601 specifies the "correct" way to represent a duration: `P2W3D`
- Simplified: `2W3D`, `2w3d`.
- Ignore the days: `2`, `2W`, `2w`
- Delimited `2(3)`, `2/3`, `2,3`, `2.3`
- Redundant `2W3D (17)`, `2,3 (17)`

**Comment by PritchardBarry** [comment]
I would go with “simplified” (2w3d).

**Comment by PritchardBarry** [comment]
... no days shown if no remainder .... I.e 
14d = 2w
15d = 2w1d
